name: build
on: push
jobs:
  build_cli:
    name: Build CLI on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Build CLI tool
        run: cargo build --release --bins
      - name: Remove dep info files
        run: rm target/release/*.d
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: target/release/rtfcre*
