name: build
on: push
jobs:
  build_cli:
    name: Build CLI on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Build CLI tool
        run: cargo build --release --bins
      - uses: actions/upload-artifact@v2
        if: ${{ runner.os == 'Linux' }}
        with:
          name: rtfcre-linux
          path: target/release/rtfcre
      - uses: actions/upload-artifact@v2
        if: ${{ runner.os == 'macOS' }}
        with:
          name: rtfcre-mac
          path: target/release/rtfcre
      - uses: actions/upload-artifact@v2
        if: ${{ runner.os == 'Windows' }}
        with:
          name: rtfcre-win.exe
          path: target/release/rtfcre.exe
